version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '4000:4000'
#    volumes:
#      - ./backend:/app
#      - ./backend/node_modules
    stdin_open: true
    tty: true
  frontend:
    build: ./frontend/my-app
    container_name: frontend
    ports:
      - '3000:3000'
#    volumes:
#      - ./frontend:/my-app
#      - ./frontend/my-app/node_modules
    stdin_open: true
    tty: true